name: CI Linux

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        BUILD_TYPE: [Debug, Release]
        COMPILER: [gcc, clang]
        include:
        - COMPILER: 'gcc'
          COMPILER_VERSION: 12
            
        - COMPILER: 'clang'
          COMPILER_VERSION: 15

    env:
      CONAN_USER_HOME: ${{github.workspace}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10'

      - name: Print Configuration
        run: |
          echo OS - ${{matrix.OS}}
          echo Compiler - ${{matrix.COMPILER}}
          echo Version - ${{matrix.COMPILER_VERSION}}
          echo BUILD_TYPE - ${{matrix.BUILD_TYPE}}
          echo CONAN_USER_HOME - ${{env.CONAN_USER_HOME}}

      - name: Create Text File
        run: echo "${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}} ${{matrix.BUILD_TYPE}}" > file-${{matrix.COMPILER}}_${{matrix.COMPILER_VERSION}}_${{matrix.BUILD_TYPE}}.txt

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{matrix.COMPILER}}_${{matrix.COMPILER_VERSION}}_${{matrix.BUILD_TYPE}}
          path: file-${{matrix.COMPILER}}_${{matrix.COMPILER_VERSION}}_${{matrix.BUILD_TYPE}}.txt

  download_artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display Contents
        run: |
          ls -l artifacts
          cat artifacts/file-gcc_12_Debug.txt
          cat artifacts/file-gcc_12_Release.txt
          cat artifacts/file-clang_15_Debug.txt
          cat artifacts/file-clang_15_Release.txt
